### PR TITLE
Fix balance update

### PR DESCRIPTION
**Pull request by jcchevalier**
fix: balance is now refreshed on restart of the application. To do so, the getUser() method has been moved from ConnexionActivity to MainActivity.

### CODE REVIEW

**Comment by jcchevalier** [comment]
It is preferable to wait beta users' returns before merging this branch

**Comment by AlexandreLadriere** [comment]
When I click on the ```change password``` option, the app is crashing. 
Trace:

```
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.mycomifclient, PID: 14469
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mycomifclient/com.example.mycomifclient.connexion.ChangePasswordActivity}: android.view.InflateException: Binary XML file line #105: Error inflating class TextView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2493)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2557)
        at android.app.ActivityThread.access$800(ActivityThread.java:176)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5578)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
     Caused by: android.view.InflateException: Binary XML file line #105: Error inflating class TextView
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at com.example.mycomifclient.connexion.ChangePasswordActivity.onCreate(ChangePasswordActivity.kt:30)
        at android.app.Activity.performCreate(Activity.java:5998)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2446)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2557) 
        at android.app.ActivityThread.access$800(ActivityThread.java:176) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5578) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750) 
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=39; index=573
        at android.content.res.StringBlock.get(StringBlock.java:65)
        at android.content.res.XmlBlock$Parser.getPooledString(XmlBlock.java:458)
        at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:967)
        at android.content.res.TypedArray.getString(TypedArray.java:176)
        at android.widget.TextView.<init>(TextView.java:1082)
        at android.widget.TextView.<init>(TextView.java:701)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:99)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:95)
        at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:182)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161) 
        at com.example.mycomifclient.connexion.ChangePasswordActivity.onCreate(ChangePasswordActivity.kt:30) 
        at android.app.Activity.performCreate(Activity.java:5998) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2446) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2557) 
        at android.app.ActivityThread.access$800(ActivityThread.java:176) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5578) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750) 

```

**Comment by AlexandreLadriere** [comment]
This issue is coming from the following text view:
```xml
TextView
        android:id="@+id/a_change_password_text_view_response"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="100dp"
        android:layout_marginEnd="100dp"
        android:textAlignment="gravity"
        android:textAllCaps="false"
        android:textColor="#DD2C00"
        app:layout_constraintBottom_toTopOf="@+id/a_change_password_button_change_password"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/a_change_password_edit_text_verified_new_password" />
```

I will try to find a solution.

**Comment by AlexandreLadriere** [comment]
The issue was coming from the ```android:textAllCaps="false"``` line. I removed it, and it is now working 100%.

**Pull request merged**
