### PR TITLE
Implement change password

### PR DESCRIPTION
**Pull request by jcchevalier**
Added an activity that allows user to change his password. Need reviews to be sure everything works fine

### CODE REVIEW

**Comment by jcchevalier** [comment]
To test this functionnality, I can add one test user to the dev database, and we can try to change the password and see if it correctly modifies the password's hash stocked inside the database

**Comment by jcchevalier** [comment]
Changes requested must have been solved during the last 3 commits. Please check out ;)

**Comment by AlexandreLadriere** [comment]
The app is crashing when I try to log in. The problem is that `this@ConnexionActivity` is used in all Toasts in `ConnexionActivity` instead of just using `this` for the context. 

It is not the first time that we have this problem.

I will modify it.

**Comment by AlexandreLadriere** [comment]
Everything is now working fine. However, I would like to test to change password for a test user. Could you create one to test it @jcchevalier ?

**Comment by jcchevalier** [comment]
I must modify the implementation server-side to do so, as I cannot add a test user inside the production database, which is used by the Comif' actually. I must do this inside the dev' database, and modify the implementation of the dev' website so it uses the dev' database from now, instead of the prod' database. I'll do this asap and you will be warned when this will be done.

**Pull request merged**
